# Generated by Django 5.2.15 on 2026-06-14 01:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_demande', models.DecimalField(decimal_places=2, max_digits=12)),
                ('duree_mois', models.PositiveIntegerField()),
                ('motif', models.TextField()),
                ('piece_justificative', models.FileField(blank=True, null=True, upload_to='pieces/')),
                ('statut', models.CharField(choices=[('soumise', 'Soumise'), ('en_analyse', 'En analyse'), ('approuvee', 'Approuvée'), ('decaissee', 'Décaissée'), ('rejetee', 'Rejetée')], default='soumise', max_length=20)),
                ('score_eligibilite', models.IntegerField(default=0)),
                ('taux_interet', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dossiers_traites', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_credit', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EcheanceRemboursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('date_echeance', models.DateField()),
                ('montant_principal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('montant_interet', models.DecimalField(decimal_places=2, max_digits=12)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('est_paye', models.BooleanField(default=False)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='echeances', to='credits.demandecredit')),
            ],
        ),
    ]
